const products = [
{
        id: 0,
        name: "itel p41",
        price: 200,
        instock: 10,
        imgSrc: "./images/phone1.jpeg",
},
{
        id: 1,
        name: "itel p42",
        price: 300,
        instock: 20,
        imgSrc: "./images/phone2.jpeg",
},
{
        id: 2,
        name: "itel p43",
        price: 400,
        instock: 30,
        imgSrc: "./images/phone3.jpeg",
},
{
        id: 3,
        name: "itel p44",
        price: 500,
        instock: 40,
        imgSrc: "./images/phone4.jpeg",
},
{
        id: 4,
        name: "itel p45",
        price: 600,
        instock: 50,
        imgSrc: "./images/phone5.jpeg",
},
{
        id: 5,
        name: "itel p46",
        price: 700,
        instock: 60,
        imgSrc: "./images/phone6.jpeg",
},
{
        id: 6,
        name: "itel p47",
        price: 800,
        instock: 70,
        imgSrc: "./images/phone7.jpeg",
}];
